### ISSUE TITLE
Question about AMD GPU performance

### ISSUE THREAD

**Issue by sajber** [bayaraa/d2gl#100]
Hi, I'm using the D2GL with the PD2 implementation so it is using an older version and AMD GPU's seem to struggle a lot with performance and FPS drops/stutter.

I believe you may have introduced something to fix this in your newer commits since then, but I'm unable to find any commits that mention it when going through them.
Could this have been fixed in any of the earlier ones with commit message "wip" or could you point me in a direction of a certain commit?

Then I will see if I can get the PD2 devs can include it in the upcoming season if easily transferable.

Thanks for the awesome work!

**Comment by bayaraa** [comment]
Hi.
Probably those wips are render thread separation commits. I was too lazy to put actual commit msgs lol.
But not just some changes to make performance better. Its buch of thing i tried/added since to current d2gl get better.
Plus i dont think they change wrapper mid season bc its untested online.
Probably they update d2gl next season i think.

**Comment by AMarquis1** [comment]
@bayaraa 
Since PD2 switched to d2gl, I've been experiencing significant performance issues. My GPU utilization never exceeds 10%, which leads to severe FPS drops during intense gameplay. When playing alone, the game runs fine (most of the time), but in scenarios with three or more players, the FPS plummets to 5-10 FPS.

Switching back to the normal PD2 (without d2gl) resolves the issue, with GPU utilization returning to normal levels (70% or more).
