### ISSUE TITLE
[PD2] Plugy crash and inventory bug (", line #151")

### ISSUE THREAD

**Issue by deeel1** [bayaraa/d2gl#8]
it seems (but I'm not sure)
that if you open the stats window and then the inventory very quickly at some point after entering the game,
the game either crashes or the inventory shifts
and there may also be some bug with putting on equipment after re-entering the game
https://imgur.com/a/t9frNlH

I also had a visual bug with the display of small charms, instead of them were thin color strips
it was resolved by re-logging, so I didn't take a screenshot

**Comment by bayaraa** [comment]
Yeah, its because very hacky way to fix pd2's stack/unstack working. Basicly apply patch when you open inventory, remove when close. Open/close faster migth be causing crash.
Do you have diablo 2's generated log file like this ``D2230228.txt`` when crash occured date. If so attach here. i wil look later.

**Comment by deeel1** [comment]
[D2230301.txt](https://github.com/bayaraa/d2gl/files/10858804/D2230301.txt)

**Comment by bayaraa** [comment]
@deeel1 in new version PD2 inventory layout bug fixed. but texture bug is still persists.

**Comment by germayneng** [comment]
Hi, i am also facing 151 crashes. Is there any fix for this? Crashing during ubers sometimes as well

**Comment by bayaraa** [comment]
come to #25. close this for now.
